### ISSUE TITLE
Support for multiple fonts

### ISSUE THREAD

**Issue by purplebar0** [sambazley/blockbar#1]
It would be nice if multiple fonts could be used, particularly for a combination such as a nice monospace font with a lesser character set and another one with a greater set.

(Idea relayed from a user without access to GitHub)

**Comment by sambazley** [comment]
Do you mean you want to use a fallback font? That should be possible by setting multiple fonts separated by commas, ie `fonta,fontb 9`.
https://docs.gtk.org/Pango/type_func.FontDescription.from_string.html#description
